
 platform :ios, '9.0'

target 'MiaoMibo' do

   use_frameworks!


   pod 'Masonry','~>1.0.2'
   pod 'MJRefresh','~>3.1.12'
   pod 'MJExtension','~>3.0.13'
   pod 'SDWebImage', '~> 3.8.1'
   pod 'ReactiveCocoa','~>2.5'
   pod 'AFNetworking', '~> 3.1.0'
   pod 'DZNEmptyDataSet'
   pod 'BarrageRenderer'
   pod 'LFLiveKit'
end
